#Requires -Version 5.1
<#
.SYNOPSIS
    Inspects game types from Il2Cpp assemblies to discover methods, fields, and properties.

.DESCRIPTION
    Loads the Il2Cpp proxy assemblies generated by MelonLoader and dumps detailed
    member information for specified types. Useful for finding correct method signatures
    for Harmony patches.

.PARAMETER Types
    Array of type names to inspect. Defaults to Server, CustomerBase, Player, TimeController.

.PARAMETER GamePath
    Override for the game installation path.

.EXAMPLE
    .\inspect_types.ps1
    .\inspect_types.ps1 -Types @('Server', 'HRSystem')
#>

param(
    [string[]]$Types = @('Server', 'CustomerBase', 'Player', 'TimeController', 'MainGameManager', 'ComputerShop', 'HRSystem', 'SaveSystem', 'NetworkMap'),
    [string]$GamePath = ""
)

$ErrorActionPreference = "Continue"

# Find game path
if (-not $GamePath) {
    $candidates = @(
        "C:\Program Files (x86)\Steam\steamapps\common\Data Center",
        "C:\Program Files\Steam\steamapps\common\Data Center",
        "D:\Steam\steamapps\common\Data Center",
        "D:\SteamLibrary\steamapps\common\Data Center",
        "E:\Steam\steamapps\common\Data Center",
        "E:\SteamLibrary\steamapps\common\Data Center"
    )

    # Also try registry
    $regPaths = @(
        "HKLM:\SOFTWARE\Valve\Steam",
        "HKLM:\SOFTWARE\WOW6432Node\Valve\Steam",
        "HKCU:\SOFTWARE\Valve\Steam"
    )

    foreach ($reg in $regPaths) {
        try {
            $regItem = Get-ItemProperty -Path $reg -ErrorAction SilentlyContinue
            if ($regItem -and $regItem.InstallPath) {
                $candidates += (Join-Path $regItem.InstallPath "steamapps\common\Data Center")

                # Also parse libraryfolders.vdf
                $vdfPath = Join-Path $regItem.InstallPath "steamapps\libraryfolders.vdf"
                if (Test-Path $vdfPath) {
                    $vdfContent = Get-Content $vdfPath -Raw
                    $pathMatches = [regex]::Matches($vdfContent, '"path"\s+"([^"]+)"')
                    foreach ($match in $pathMatches) {
                        $libPath = $match.Groups[1].Value -replace '\\\\', '\'
                        $candidates += (Join-Path $libPath "steamapps\common\Data Center")
                    }
                }
            }
        } catch { }
    }

    foreach ($candidate in $candidates) {
        if (Test-Path (Join-Path $candidate "Data Center.exe")) {
            $GamePath = $candidate
            break
        }
    }
}

if (-not $GamePath -or -not (Test-Path $GamePath)) {
    Write-Host "ERROR: Could not find Data Center installation." -ForegroundColor Red
    Write-Host "Please specify -GamePath parameter." -ForegroundColor Yellow
    exit 1
}

$il2cppDir = Join-Path $GamePath "MelonLoader\Il2CppAssemblies"
$net6Dir = Join-Path $GamePath "MelonLoader\net6"

if (-not (Test-Path $il2cppDir)) {
    Write-Host "ERROR: Il2CppAssemblies directory not found at: $il2cppDir" -ForegroundColor Red
    Write-Host "Make sure MelonLoader has been run at least once." -ForegroundColor Yellow
    exit 1
}

Write-Host ""
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host "    Data Center Type Inspector" -ForegroundColor Cyan
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Game path: $GamePath" -ForegroundColor Gray
Write-Host ""

# Preload all assemblies for dependency resolution
Write-Host "  Loading assemblies..." -ForegroundColor Gray

$loadedCount = 0
$assemblies = @{}

foreach ($dir in @($net6Dir, $il2cppDir)) {
    if (-not (Test-Path $dir)) { continue }
    foreach ($dll in (Get-ChildItem -Path $dir -Filter '*.dll' -ErrorAction SilentlyContinue)) {
        try {
            $asm = [System.Reflection.Assembly]::LoadFile($dll.FullName)
            $assemblies[$dll.Name] = $asm
            $loadedCount++
        } catch { }
    }
}

Write-Host "  Loaded $loadedCount assemblies." -ForegroundColor Gray
Write-Host ""

# Output file
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$outputFile = Join-Path $ScriptDir "type_dump_output.txt"
$output = [System.Text.StringBuilder]::new()

function Format-TypeName {
    param([Type]$Type)
    if ($null -eq $Type) { return "void" }
    $name = $Type.Name
    if ($Type.IsGenericType) {
        $baseName = $name -replace '`\d+$', ''
        $genericArgs = ($Type.GetGenericArguments() | ForEach-Object { Format-TypeName $_ }) -join ', '
        return "$baseName<$genericArgs>"
    }
    switch ($name) {
        'Void' { return 'void' }
        'Boolean' { return 'bool' }
        'Int32' { return 'int' }
        'Int64' { return 'long' }
        'Single' { return 'float' }
        'Double' { return 'double' }
        'String' { return 'string' }
        'UInt32' { return 'uint' }
        'UInt64' { return 'ulong' }
        'Byte' { return 'byte' }
        default { return $name }
    }
}

function Dump-TypeInfo {
    param(
        [string]$TypeName,
        [System.Text.StringBuilder]$sb
    )

    $found = $false

    foreach ($asmEntry in $assemblies.GetEnumerator()) {
        $allTypes = $null
        try {
            $allTypes = $asmEntry.Value.GetTypes()
        } catch [System.Reflection.ReflectionTypeLoadException] {
            $allTypes = $_.Exception.Types | Where-Object { $_ -ne $null }
        } catch {
            continue
        }

        if ($null -eq $allTypes) { continue }

        $matchedTypes = $allTypes | Where-Object {
            $_ -ne $null -and ($_.Name -eq $TypeName -or $_.FullName -eq $TypeName)
        }

        foreach ($type in $matchedTypes) {
            $found = $true
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine("================================================================================") | Out-Null
            $sb.AppendLine("  TYPE: $($type.FullName)") | Out-Null
            $sb.AppendLine("  Assembly: $($asmEntry.Key)") | Out-Null
            if ($type.BaseType) {
                $sb.AppendLine("  BaseType: $($type.BaseType.FullName)") | Out-Null
            }
            $sb.AppendLine("  IsPublic: $($type.IsPublic)  IsAbstract: $($type.IsAbstract)  IsSealed: $($type.IsSealed)") | Out-Null
            $sb.AppendLine("================================================================================") | Out-Null

            # --- Fields ---
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine("  --- FIELDS ---") | Out-Null

            $fields = $type.GetFields([System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::NonPublic -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::Static -bor
                [System.Reflection.BindingFlags]::DeclaredOnly)

            if ($fields.Count -eq 0) {
                $sb.AppendLine("    (none)") | Out-Null
            }

            foreach ($field in ($fields | Sort-Object { $_.IsStatic }, Name)) {
                $access = if ($field.IsPublic) { "public" }
                          elseif ($field.IsFamily) { "protected" }
                          elseif ($field.IsPrivate) { "private" }
                          else { "internal" }
                $static = if ($field.IsStatic) { " static" } else { "" }
                $typeName = Format-TypeName $field.FieldType
                $sb.AppendLine("    $access$static $typeName $($field.Name)") | Out-Null
            }

            # --- Properties ---
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine("  --- PROPERTIES ---") | Out-Null

            $props = $type.GetProperties([System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::NonPublic -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::Static -bor
                [System.Reflection.BindingFlags]::DeclaredOnly)

            if ($props.Count -eq 0) {
                $sb.AppendLine("    (none)") | Out-Null
            }

            foreach ($prop in ($props | Sort-Object Name)) {
                $typeName = Format-TypeName $prop.PropertyType
                $getter = if ($prop.GetGetMethod($true)) { "get; " } else { "" }
                $setter = if ($prop.GetSetMethod($true)) { "set; " } else { "" }
                $static = ""
                $getMethod = $prop.GetGetMethod($true)
                if ($null -eq $getMethod) { $getMethod = $prop.GetSetMethod($true) }
                if ($null -ne $getMethod -and $getMethod.IsStatic) { $static = " static" }
                $sb.AppendLine("    $typeName$static $($prop.Name) { $getter$setter}") | Out-Null
            }

            # --- Methods ---
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine("  --- METHODS ---") | Out-Null

            $methods = $type.GetMethods([System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::NonPublic -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::Static -bor
                [System.Reflection.BindingFlags]::DeclaredOnly) |
                Where-Object {
                    -not $_.IsSpecialName
                }

            if ($methods.Count -eq 0) {
                $sb.AppendLine("    (none)") | Out-Null
            }

            foreach ($method in ($methods | Sort-Object { $_.IsStatic }, Name)) {
                $access = if ($method.IsPublic) { "public" }
                          elseif ($method.IsFamily) { "protected" }
                          elseif ($method.IsPrivate) { "private" }
                          else { "internal" }
                $static = if ($method.IsStatic) { " static" } else { "" }
                $virtual = if ($method.IsVirtual -and -not $method.IsFinal) { " virtual" } else { "" }
                $override = if ($method.IsVirtual -and $method.GetBaseDefinition().DeclaringType -ne $type) { " override" } else { "" }
                $retType = Format-TypeName $method.ReturnType

                $params = ($method.GetParameters() | ForEach-Object {
                    $pType = Format-TypeName $_.ParameterType
                    $pDefault = ""
                    if ($_.HasDefaultValue) {
                        if ($null -eq $_.DefaultValue) { $pDefault = " = null" }
                        elseif ($_.DefaultValue -is [bool]) { $pDefault = " = " + $_.DefaultValue.ToString().ToLower() }
                        elseif ($_.DefaultValue -is [string]) { $pDefault = " = `"$($_.DefaultValue)`"" }
                        else { $pDefault = " = $($_.DefaultValue)" }
                    }
                    "$pType $($_.Name)$pDefault"
                }) -join ', '

                $sb.AppendLine("    $access$static$virtual$override $retType $($method.Name)($params)") | Out-Null
            }

            # --- Events ---
            $events = $type.GetEvents([System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::NonPublic -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::Static -bor
                [System.Reflection.BindingFlags]::DeclaredOnly)

            if ($events.Count -gt 0) {
                $sb.AppendLine("") | Out-Null
                $sb.AppendLine("  --- EVENTS ---") | Out-Null
                foreach ($evt in ($events | Sort-Object Name)) {
                    $handlerType = Format-TypeName $evt.EventHandlerType
                    $sb.AppendLine("    event $handlerType $($evt.Name)") | Out-Null
                }
            }

            $sb.AppendLine("") | Out-Null
        }
    }

    if (-not $found) {
        $sb.AppendLine("") | Out-Null
        $sb.AppendLine("  TYPE NOT FOUND: $TypeName") | Out-Null
        $sb.AppendLine("") | Out-Null

        # Try fuzzy match
        $fuzzyMatches = @()
        foreach ($asmEntry in $assemblies.GetEnumerator()) {
            try {
                $allTypes = $asmEntry.Value.GetTypes()
            } catch [System.Reflection.ReflectionTypeLoadException] {
                $allTypes = $_.Exception.Types | Where-Object { $_ -ne $null }
            } catch {
                continue
            }
            if ($null -eq $allTypes) { continue }

            $fuzzyMatches += $allTypes | Where-Object {
                $_ -ne $null -and $_.Name -like "*$TypeName*"
            }
        }

        if ($fuzzyMatches.Count -gt 0) {
            $sb.AppendLine("  Possible matches:") | Out-Null
            foreach ($m in ($fuzzyMatches | Sort-Object FullName | Select-Object -First 20)) {
                $sb.AppendLine("    - $($m.FullName) (in $($m.Assembly.GetName().Name))") | Out-Null
            }
            $sb.AppendLine("") | Out-Null
        }
    }
}

# Dump each requested type
foreach ($typeName in $Types) {
    Write-Host "  Inspecting: $typeName ..." -ForegroundColor White
    Dump-TypeInfo -TypeName $typeName -sb $output
}

# Write output to file and console
$result = $output.ToString()
Set-Content -Path $outputFile -Value $result -Encoding UTF8

Write-Host ""
Write-Host "  Output saved to: $outputFile" -ForegroundColor Green
Write-Host ""

# Also print to console
Write-Host $result

Write-Host ""
Write-Host "  Done." -ForegroundColor Cyan
